### ISSUE TITLE
Use of smart/programmable splitters (optional)

### ISSUE THREAD

**Issue by rdc74656** [AnthorNet/SC-ProductionPlanner#10]
Just a thought since I’ve unlocked them.  Maybe have an option to incorporate smart/programmable splitters into production chain to reduce belts needed, I know this is a learning curve for end-user but just a suggestion.

**Comment by jhechtf** [comment]
This is more just a question about the game but why would that be preferable? I could see that being prone to issues if too many of one thing are in the belt. I'm not against it I just don't see why it would be something I'd want to do.

**Comment by rdc74656** [comment]
To be honest matey I’m still coming to grips with the game and I’m thick, I like things to be planned (which is why this production planner is such a god send) when it comes to me designing stuff I just can’t, I’m not that artistic, I like to see something drawn out for me and then layed down in a plan for me to follow, so I thought if smart splitters could be incorporated as an optimal use, I could maybe see where my belts would benefit from that...also can anyone see a distinct difference between programmable and smart splitters because to me it looks like they do the same thing.

**Comment by jhechtf** [comment]
the difference i know of between smart and programmable splitters is that programmable splitters can have multiple things output to the same side, i.e. a smart splitter can only split 1 item out for left, forward, right, but a programmable splitter could do something like plates and rods left, other forward, etc. I could see this being useful for having a dump sorter (or as we call it my combined save, the "Amazon Warehouse.") but you can achieve this by just filtering out 1 item at a time.

**Comment by AnthorNet** [comment]
It might be too hard for the scope of the production planner
