### ISSUE TITLE
Splitters do not always split equally, leading to mergers accepting too many belts

### ISSUE THREAD

**Issue by Thanatomanic** [AnthorNet/SC-ProductionPlanner#103]
Unless I am misunderstanding some game mechanic, I think there is a problem in the way splitters and mergers are working in the planner. Take a look below: the splitters split into unequal parts, 10 and 20. This could be considered valid if you use all three output belts (1×10 and 2×10 = 20). However, the algorithm happily accepts 2 'double belts' into a single merger. This is impossible to replicate in game, where you would actually need another merger.

Is there some way to modify the algorithm to account for this?

![image](https://github.com/user-attachments/assets/8a715100-983b-42ab-a4d7-278283012411)

**Comment by philou-felin** [comment]
I _think_ those stats are what you can expect once your machines are full/overloaded. 🤔

I'm noob, so I might be wrong...

**Comment by AnthorNet** [comment]
That is manifold, if we added all mergers and splitters it would not be possible to see anything ^^
