### ISSUE TITLE
Unable to deselect Quartz Purification alternate recipe in the Production Planner

### ISSUE THREAD

**Issue by michaelroyer1** [AnthorNet/SC-ProductionPlanner#104]
**Issue:**

I'm currently using the production planner to make Fused Modular Frames (5/min). The Quartz Purification recipe requires Nitric Acid to make, which I have not unlocked yet (b/c I need Fused Modular Frames to do so). After realizing this I tried to deselect the Quartz Purification recipe from the list. 

The network graph buffers once and then a second time, but the node for Quartz Purification is still there, even though it is now not selected in the list.

Edit:  Note - I could be wrong, but this doesn't seem to happen with any other recipe I have unlocked.

**Steps to reproduce:** 

1. Configure the production planner to make 5 Fused Modular Frames per minute. 
2. Sync recipes from a save file that includes Quarz Purification as one of them. Here is my save file if needed: [Main Save.zip](https://github.com/user-attachments/files/17725877/Main.Save.zip)
3. Attempt to deselect the Quartz Purification recipe from the alternate recipes dropdown.
   - Notice the checkbox disappears and the network graph reloads, but the Quartz Purification recipe has been re-selected without clicking on it again.

![chrome_slIzhXOUpv](https://github.com/user-attachments/assets/439ef52f-4797-420c-bc89-db376db83e57)

The recipes I have unlocked (I haven't gone through to note which ones are being used in the network graph currently):
- Residual Fuel
- Residual Plastic
- Residual Rubber
- Wet Concrete
- Steel Rod
- Steamed Copper Sheet
- Pure Quartz Crystal
- Pure Caterium Ingot
- Polymer Resin
- Flexible Framework
- Electrode Circuit Board
- Electrode Aluminum Scrap
- Copper Rotor
- Coke Steel Ingot
- Coated Cable
- Bolted Frame
- Diluted Fuel
- Molded Steel Pipe
- Iron Pipe
- Molded Beam
- Plastic AI Limiter
- Distilled Silica
- **Quartz Purification**
- Fused Quartz Crystal
- Quickwire Stator
- Cheap Silica
- Steel Screw
- Cast Screw
- Uranium Fuel Unit
- Solid Steel Ingot
- Silicon High-Speed Connector
- Heat Exchanger
- Caterium Computer
- Caterium Circuit Board
- Quickwire Cable

**Comment by AnthorNet** [comment]
Please share the link so I get the exact same situation

**Comment by AnthorNet** [comment]
Most likely related to this:
https://github.com/AnthorNet/SC-ProductionPlanner/blob/main/src/Worker/Wrapper.js#L609

You have Distilled Silica but no recipe to get to it, so we need to activate the Quartz purification

**Comment by michaelroyer1** [comment]
Here is the exact link

> https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_ModularFrameFused_C%22%3A%225%22%2C%22altRecipes%22%3A%5B%22Recipe_ResidualFuel_C%22%2C%22Recipe_ResidualPlastic_C%22%2C%22Recipe_ResidualRubber_C%22%2C%22Recipe_Alternate_WetConcrete_C%22%2C%22Recipe_Alternate_SteelRod_C%22%2C%22Recipe_Alternate_SteamedCopperSheet_C%22%2C%22Recipe_Alternate_PureQuartzCrystal_C%22%2C%22Recipe_Alternate_PureCateriumIngot_C%22%2C%22Recipe_Alternate_PolymerResin_C%22%2C%22Recipe_Alternate_FlexibleFramework_C%22%2C%22Recipe_Alternate_ElectrodeCircuitBoard_C%22%2C%22Recipe_Alternate_ElectroAluminumScrap_C%22%2C%22Recipe_Alternate_CopperRotor_C%22%2C%22Recipe_Alternate_CokeSteelIngot_C%22%2C%22Recipe_Alternate_CoatedCable_C%22%2C%22Recipe_Alternate_BoltedFrame_C%22%2C%22Recipe_Alternate_DilutedFuel_C%22%2C%22Recipe_Alternate_SteelPipe_Molded_C%22%2C%22Recipe_Alternate_SteelPipe_Iron_C%22%2C%22Recipe_Alternate_SteelBeam_Molded_C%22%2C%22Recipe_Alternate_AILimiter_Plastic_C%22%2C%22Recipe_Alternate_Silica_Distilled_C%22%2C%22Recipe_Alternate_Quartz_Purified_C%22%2C%22Recipe_Alternate_Quartz_Fused_C%22%2C%22Recipe_Alternate_Stator_C%22%2C%22Recipe_Alternate_Silica_C%22%2C%22Recipe_Alternate_Screw_2_C%22%2C%22Recipe_Alternate_Screw_C%22%2C%22Recipe_Alternate_NuclearFuelRod_1_C%22%2C%22Recipe_Alternate_IngotSteel_1_C%22%2C%22Recipe_Alternate_HighSpeedConnector_C%22%2C%22Recipe_Alternate_HeatSink_1_C%22%2C%22Recipe_Alternate_Computer_1_C%22%2C%22Recipe_Alternate_CircuitBoard_2_C%22%2C%22Recipe_Alternate_Cable_2_C%22%5D%7D

**Comment by michaelroyer1** [comment]
> Most likely related to this: https://github.com/AnthorNet/SC-ProductionPlanner/blob/main/src/Worker/Wrapper.js#L609
> 
> You have Distilled Silica but no recipe to get to it, so we need to activate the Quartz purification

yeah I think you're right, I deselected Distilled Silica and I think I'm good for now. There might be a better way to handle that, but it's up to you if you want to just close this one `¯\_(ツ)_/¯`

**Comment by AnthorNet** [comment]
That's because Distilled Silica has no recipe beside being a by-product of Quartz purification
