### ISSUE TITLE
Difference between browsers in using Rubber recipe

### ISSUE THREAD

**Issue by OktopCZ** [AnthorNet/SC-ProductionPlanner#11]
Hi,
me and my friend use your planner but sometimes he had problems with recipes. After some discussion and exchange of setting we couldn´t find any problem but he still saw difference in using same recipe as me. He use Firefox and I use Chrome. I attached images from both browsers with using same setting and recipe (chrome and firefox).

It seems that when you select recipe with using Rubber in Firefox Planner try to use recipe Residual Rubber instead. It still try to use it even if you try force using Rubber recipe with selection Rubber with Rubber recipe for additional output (firefox 2). 

Thanks

OktopCZ

![firefox](https://user-images.githubusercontent.com/79104990/107976625-27f68680-6fba-11eb-9c6e-b198686ba859.jpg)
![chrome](https://user-images.githubusercontent.com/79104990/107976627-2927b380-6fba-11eb-981d-f441a90ebee9.jpg)
![firefox 2](https://user-images.githubusercontent.com/79104990/107976629-29c04a00-6fba-11eb-83f0-bd9a53b89bb0.jpg)

**Comment by AnthorNet** [comment]
Will be added when update 4 release.
