### ISSUE TITLE
[Feature Request] Determine item output by resource input

### ISSUE THREAD

**Issue by jhechtf** [AnthorNet/SC-ProductionPlanner#13]
Sometimes i want to know how much of something i can make if i have X of a resource type being pulled from a miner.

e.g. "If I am pulling 120 iron ore per minute, how many Reinforced plates can I make per minute?" 

I'm not too finicky about the output, a number would be fine for me as I could always set the requisite number of machines up and work backwards building the factory from there, but it would be nice to see a generated graph. Perhaps after calculating the value it would then be able to set that as an added item in the planner? I am willing to discuss some design meetings, but i won't be able to help on the coding for at least a few weeks.

**Comment by rdc74656** [comment]
Would like this too

**Comment by PirateAE** [comment]
I would like this also. 

Something along the lines of i have 2 Normal nodes and 2 impure nodes as my sources, How do i get what i want out of this. 

If needed, the planer could request and/or note if overclocking is needed, and adapt to that. and if its simply not able to come up with a solve, it should give what it can, and note whats needed input wise to actually achieve the targets.

**Comment by PirateAE** [comment]
> 
> 
> Should be easy now with the new input to add miners that you have

I dont see an option, only to specify what miner tier and quality, not each exact node available.

**Comment by AnthorNet** [comment]
Sadly the way calculation works are reversed, so end to start ;)

**Comment by jhechtf** [comment]
Yes, I understand that, thus why I am requesting this as a feature.
