### ISSUE TITLE
i am trting to get the employee of the planet, and tryed to use the calculator but this happened

### ISSUE THREAD

**Issue by yeetmanthecoolman** [AnthorNet/SC-ProductionPlanner#19]
[]([](https://satisfactory-calculator.com/en/production-planner/index/index/json/%7B%22Desc_SpaceElevatorPart_7_C%22%3A%224%22%2C%22Desc_SpaceElevatorPart_6_C%22%3A%224%22%2C%22Desc_SpaceElevatorPart_8_C%22%3A%221%22%2C%22Desc_SpaceElevatorPart_9_C%22%3A%221%22%2C%22Desc_PlutoniumWaste_C%22%3A%229%22%2C%22oreExtraction%22%3A%22Build_MinerMk3_C%3Bpure%22%2C%22oilExtraction%22%3A%22Build_FrackingExtractor_C%3Bpure%22%2C%22waterExtraction%22%3A%22Build_FrackingExtractor_C%3Bpure%22%2C%22gasExtraction%22%3A%22Build_FrackingExtractor_C%3Bpure%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_AdheredIronPlate_C%22%2C%22Recipe_Alternate_BoltedFrame_C%22%2C%22Recipe_Alternate_CoatedCable_C%22%2C%22Recipe_Alternate_CoatedIronCanister_C%22%2C%22Recipe_Alternate_CoatedIronPlate_C%22%2C%22Recipe_Alternate_CokeSteelIngot_C%22%2C%22Recipe_Alternate_CopperAlloyIngot_C%22%2C%22Recipe_Alternate_CopperRotor_C%22%2C%22Recipe_Alternate_DilutedPackagedFuel_C%22%2C%22Recipe_Alternate_ElectroAluminumScrap_C%22%2C%22Recipe_Alternate_ElectrodeCircuitBoard_C%22%2C%22Recipe_Alternate_FlexibleFramework_C%22%2C%22Recipe_Alternate_FusedWire_C%22%2C%22Recipe_Alternate_HeavyFlexibleFrame_C%22%2C%22Recipe_Alternate_HeavyOilResidue_C%22%2C%22Recipe_Alternate_HighSpeedWiring_C%22%2C%22Recipe_Alternate_PlasticSmartPlating_C%22%2C%22Recipe_Alternate_PolyesterFabric_C%22%2C%22Recipe_Alternate_PolymerResin_C%22%2C%22Recipe_PureAluminumIngot_C%22%2C%22Recipe_Alternate_PureCateriumIngot_C%22%2C%22Recipe_Alternate_PureCopperIngot_C%22%2C%22Recipe_Alternate_PureIronIngot_C%22%2C%22Recipe_Alternate_PureQuartzCrystal_C%22%2C%22Recipe_Alternate_RecycledRubber_C%22%2C%22Recipe_Alternate_RubberConcrete_C%22%2C%22Recipe_Alternate_SteamedCopperSheet_C%22%2C%22Recipe_Alternate_SteelCanister_C%22%2C%22Recipe_Alternate_SteelCoatedPlate_C%22%2C%22Recipe_Alternate_SteelRod_C%22%2C%22Recipe_Alternate_EnrichedCoal_C%22%2C%22Recipe_Alternate_TurboHeavyFuel_C%22%2C%22Recipe_Alternate_WetConcrete_C%22%2C%22Recipe_Alternate_AlcladCasing_C%22%2C%22Recipe_Alternate_AutomatedMiner_C%22%2C%22Recipe_Alternate_ClassicBattery_C%22%2C%22Recipe_Alternate_CoolingDevice_C%22%2C%22Recipe_Alternate_DilutedFuel_C%22%2C%22Recipe_Alternate_ElectricMotor_C%22%2C%22Recipe_Alternate_FertileUranium_C%22%2C%22Recipe_Alternate_HeatFusedFrame_C%22%2C%22Recipe_Alternate_InstantPlutoniumCell_C%22%2C%22Recipe_Alternate_InstantScrap_C%22%2C%22Recipe_Alternate_OCSupercomputer_C%22%2C%22Recipe_Alternate_PlutoniumFuelUnit_C%22%2C%22Recipe_Alternate_RadioControlSystem_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%2C%22Recipe_Alternate_SuperStateComputer_C%22%2C%22Recipe_Alternate_TurboBlendFuel_C%22%2C%22Recipe_Alternate_TurboPressureMotor_C%22%2C%22Recipe_Alternate_Beacon_1_C%22%2C%22Recipe_Alternate_Cable_1_C%22%2C%22Recipe_Alternate_Cable_2_C%22%2C%22Recipe_Alternate_CircuitBoard_1_C%22%2C%22Recipe_Alternate_CircuitBoard_2_C%22%2C%22Recipe_Alternate_Coal_1_C%22%2C%22Recipe_Alternate_Coal_2_C%22%2C%22Recipe_Alternate_Computer_1_C%22%2C%22Recipe_Alternate_Computer_2_C%22%2C%22Recipe_Alternate_Concrete_C%22%2C%22Recipe_Alternate_CrystalOscillator_C%22%2C%22Recipe_Alternate_ElectromagneticControlRod_1_C%22%2C%22Recipe_Alternate_Gunpowder_1_C%22%2C%22Recipe_Alternate_HeatSink_1_C%22%2C%22Recipe_Alternate_ModularFrameHeavy_C%22%2C%22Recipe_Alternate_HighSpeedConnector_C%22%2C%22Recipe_Alternate_IngotIron_C%22%2C%22Recipe_Alternate_IngotSteel_1_C%22%2C%22Recipe_Alternate_IngotSteel_2_C%22%2C%22Recipe_Alternate_ModularFrame_C%22%2C%22Recipe_Alternate_Motor_1_C%22%2C%22Recipe_Alternate_Nobelisk_1_C%22%2C%22Recipe_Alternate_NuclearFuelRod_1_C%22%2C%22Recipe_Alternate_Plastic_1_C%22%2C%22Recipe_Alternate_Quickwire_C%22%2C%22Recipe_Alternate_RadioControlUnit_1_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_1_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_2_C%22%2C%22Recipe_Alternate_EncasedIndustrialBeam_C%22%2C%22Recipe_Alternate_Rotor_C%22%2C%22Recipe_Alternate_Screw_C%22%2C%22Recipe_Alternate_Screw_2_C%22%2C%22Recipe_Alternate_Silica_C%22%2C%22Recipe_Alternate_Stator_C%22%2C%22Recipe_Alternate_Turbofuel_C%22%2C%22Recipe_Alternate_TurboMotor_1_C%22%2C%22Recipe_Alternate_UraniumCell_1_C%22%2C%22Recipe_Alternate_Wire_1_C%22%2C%22Recipe_Alternate_Wire_2_C%22%5D%2C%22powerShards%22%3A%2210000000%22%7D)
)gave "SBOX_FATAL_MEMORY_EXCEEDED" or somthing like that.

**Comment by yeetmanthecoolman** [comment]
https://satisfactory-calculator.com/en/production-planner/index/index/json/%7B%22Desc_SpaceElevatorPart_7_C%22%3A%224%22%2C%22Desc_SpaceElevatorPart_6_C%22%3A%224%22%2C%22Desc_SpaceElevatorPart_8_C%22%3A%221%22%2C%22Desc_SpaceElevatorPart_9_C%22%3A%221%22%2C%22Desc_PlutoniumWaste_C%22%3A%229%22%2C%22oreExtraction%22%3A%22Build_MinerMk3_C%3Bpure%22%2C%22oilExtraction%22%3A%22Build_FrackingExtractor_C%3Bpure%22%2C%22waterExtraction%22%3A%22Build_FrackingExtractor_C%3Bpure%22%2C%22gasExtraction%22%3A%22Build_FrackingExtractor_C%3Bpure%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_AdheredIronPlate_C%22%2C%22Recipe_Alternate_BoltedFrame_C%22%2C%22Recipe_Alternate_CoatedCable_C%22%2C%22Recipe_Alternate_CoatedIronCanister_C%22%2C%22Recipe_Alternate_CoatedIronPlate_C%22%2C%22Recipe_Alternate_CokeSteelIngot_C%22%2C%22Recipe_Alternate_CopperAlloyIngot_C%22%2C%22Recipe_Alternate_CopperRotor_C%22%2C%22Recipe_Alternate_DilutedPackagedFuel_C%22%2C%22Recipe_Alternate_ElectroAluminumScrap_C%22%2C%22Recipe_Alternate_ElectrodeCircuitBoard_C%22%2C%22Recipe_Alternate_FlexibleFramework_C%22%2C%22Recipe_Alternate_FusedWire_C%22%2C%22Recipe_Alternate_HeavyFlexibleFrame_C%22%2C%22Recipe_Alternate_HeavyOilResidue_C%22%2C%22Recipe_Alternate_HighSpeedWiring_C%22%2C%22Recipe_Alternate_PlasticSmartPlating_C%22%2C%22Recipe_Alternate_PolyesterFabric_C%22%2C%22Recipe_Alternate_PolymerResin_C%22%2C%22Recipe_PureAluminumIngot_C%22%2C%22Recipe_Alternate_PureCateriumIngot_C%22%2C%22Recipe_Alternate_PureCopperIngot_C%22%2C%22Recipe_Alternate_PureIronIngot_C%22%2C%22Recipe_Alternate_PureQuartzCrystal_C%22%2C%22Recipe_Alternate_RecycledRubber_C%22%2C%22Recipe_Alternate_RubberConcrete_C%22%2C%22Recipe_Alternate_SteamedCopperSheet_C%22%2C%22Recipe_Alternate_SteelCanister_C%22%2C%22Recipe_Alternate_SteelCoatedPlate_C%22%2C%22Recipe_Alternate_SteelRod_C%22%2C%22Recipe_Alternate_EnrichedCoal_C%22%2C%22Recipe_Alternate_TurboHeavyFuel_C%22%2C%22Recipe_Alternate_WetConcrete_C%22%2C%22Recipe_Alternate_AlcladCasing_C%22%2C%22Recipe_Alternate_AutomatedMiner_C%22%2C%22Recipe_Alternate_ClassicBattery_C%22%2C%22Recipe_Alternate_CoolingDevice_C%22%2C%22Recipe_Alternate_DilutedFuel_C%22%2C%22Recipe_Alternate_ElectricMotor_C%22%2C%22Recipe_Alternate_FertileUranium_C%22%2C%22Recipe_Alternate_HeatFusedFrame_C%22%2C%22Recipe_Alternate_InstantPlutoniumCell_C%22%2C%22Recipe_Alternate_InstantScrap_C%22%2C%22Recipe_Alternate_OCSupercomputer_C%22%2C%22Recipe_Alternate_PlutoniumFuelUnit_C%22%2C%22Recipe_Alternate_RadioControlSystem_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%2C%22Recipe_Alternate_SuperStateComputer_C%22%2C%22Recipe_Alternate_TurboBlendFuel_C%22%2C%22Recipe_Alternate_TurboPressureMotor_C%22%2C%22Recipe_Alternate_Beacon_1_C%22%2C%22Recipe_Alternate_Cable_1_C%22%2C%22Recipe_Alternate_Cable_2_C%22%2C%22Recipe_Alternate_CircuitBoard_1_C%22%2C%22Recipe_Alternate_CircuitBoard_2_C%22%2C%22Recipe_Alternate_Coal_1_C%22%2C%22Recipe_Alternate_Coal_2_C%22%2C%22Recipe_Alternate_Computer_1_C%22%2C%22Recipe_Alternate_Computer_2_C%22%2C%22Recipe_Alternate_Concrete_C%22%2C%22Recipe_Alternate_CrystalOscillator_C%22%2C%22Recipe_Alternate_ElectromagneticControlRod_1_C%22%2C%22Recipe_Alternate_Gunpowder_1_C%22%2C%22Recipe_Alternate_HeatSink_1_C%22%2C%22Recipe_Alternate_ModularFrameHeavy_C%22%2C%22Recipe_Alternate_HighSpeedConnector_C%22%2C%22Recipe_Alternate_IngotIron_C%22%2C%22Recipe_Alternate_IngotSteel_1_C%22%2C%22Recipe_Alternate_IngotSteel_2_C%22%2C%22Recipe_Alternate_ModularFrame_C%22%2C%22Recipe_Alternate_Motor_1_C%22%2C%22Recipe_Alternate_Nobelisk_1_C%22%2C%22Recipe_Alternate_NuclearFuelRod_1_C%22%2C%22Recipe_Alternate_Plastic_1_C%22%2C%22Recipe_Alternate_Quickwire_C%22%2C%22Recipe_Alternate_RadioControlUnit_1_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_1_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_2_C%22%2C%22Recipe_Alternate_EncasedIndustrialBeam_C%22%2C%22Recipe_Alternate_Rotor_C%22%2C%22Recipe_Alternate_Screw_C%22%2C%22Recipe_Alternate_Screw_2_C%22%2C%22Recipe_Alternate_Silica_C%22%2C%22Recipe_Alternate_Stator_C%22%2C%22Recipe_Alternate_Turbofuel_C%22%2C%22Recipe_Alternate_TurboMotor_1_C%22%2C%22Recipe_Alternate_UraniumCell_1_C%22%2C%22Recipe_Alternate_Wire_1_C%22%2C%22Recipe_Alternate_Wire_2_C%22%5D%2C%22powerShards%22%3A%2210000000%22%7D
gave it

**Comment by Thoreas** [comment]
Using the link you provided:

![image](https://user-images.githubusercontent.com/44213940/115792638-ed9ad280-a3ca-11eb-893f-546ca5efe02b.png)

I'd say it's your PC running out of available memory. This tab alone uses almost 9GB of RAM:

![image](https://user-images.githubusercontent.com/44213940/115792703-099e7400-a3cb-11eb-8e89-63e1eb097991.png)

**Comment by AnthorNet** [comment]
Make 5 tabs instead of trying to get too much on the same request should solve your problem.

**Comment by yeetmanthecoolman** [comment]
thanks!
