### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by shawnphoffman** [AnthorNet/SC-ProductionPlanner#2]
This is not an issue.

If you're interested, I'd love to help contribute to this project. I really like the production planner and I think it would be cool to help expand the capabilities beyond the "expected output" scenario. I recognize that we're all busy but wanted to reach out just in case.

Thanks!

**Comment by AnthorNet** [comment]
Hello,
The plan is too release most of the code! But I've got caught in some real life trouble I need to handle and complete before going full speed again 👍

**Comment by jhechtf** [comment]
I'm also willing to help; currently work as a front-end engineer but i have experience in other areas if that might be helpful.
