### ISSUE TITLE
Building count not represented correctly in Simple View Mode

### ISSUE THREAD

**Issue by DechertNicholas** [AnthorNet/SC-ProductionPlanner#20]
If the production planner is set to "View Mode: Simple", the "Buildings" tab only counts the nodes in the planner, not the number those nodes represent. For instance, with 2.5 Automated Wiring per minute in the planner, the "Building" tab will show the plan as needing only three constructors, when it should actually be seven.

With "View Mode: Realistic" - correct number of buildings displayed
![image](https://user-images.githubusercontent.com/69116680/117093483-f0c08780-ad15-11eb-8633-8349d8f2f609.png)

With "View Mode: Simple" - incorrect number of buildings displayed
![image](https://user-images.githubusercontent.com/69116680/117093544-1b124500-ad16-11eb-8fde-6bfc5a0b0320.png)

Looks like it only counts the nodes, not the number those nodes represent
![image](https://user-images.githubusercontent.com/69116680/117093590-367d5000-ad16-11eb-98f1-625b617e19a5.png)

**Comment by Thoreas** [comment]
In your last screenshot, the leftmost Constructor says "x4 Constructor". The one right to it is "x1.7 Constructor", so that's 2 Constructors if you're not overclocking, and the bottom one says "x0.4 Constructor", so that's 1.

4+2+1 = 7

I see no issue here.

**Comment by AnthorNet** [comment]
Yes 7 not 3 as stated in the simple list.
It's because there is only 3 nodes, but that will be fixed :)
