### ISSUE TITLE
[Feature Request] Minimal input under 1 per minute

### ISSUE THREAD

**Issue by Gotcha26** [AnthorNet/SC-ProductionPlanner#24]
Some items (ex : "Assembly director system" [0.75 / min] & "Nuclear pasta" [0.5 / min]), to plan their production on a single machine (100%), the pace (yield) is under 1 per minute.
But the field form accept only 1 or more. So, isn't possible to plan a production in this case.

Thanks.

**Comment by AnthorNet** [comment]
Fix like #17
