### ISSUE TITLE
unnecessary splitting across several machines

### ISSUE THREAD

**Issue by Snowcreeper** [AnthorNet/SC-ProductionPlanner#25]
All pipes/conveyorbelts would be able to transfer the whole amount required/produced.
Why doesn't it show 1 refinery running at 98%?

![Image 003](https://user-images.githubusercontent.com/65914203/119798947-e9873680-bedb-11eb-9600-d7ab958f5815.png)

**Comment by AnthorNet** [comment]
Hello,
Could you sendenthe direct link?

**Comment by Snowcreeper** [comment]
this link?
https://satisfactory-calculator.com/en/production-planner/index/index/json/%7B%22Desc_ModularFrameFused_C%22%3A%221.5%22%2C%22Desc_MotorLightweight_C%22%3A%221%22%2C%22input%22%3A%7B%22Desc_Coal_C%22%3A%22480%22%2C%22Desc_RawQuartz_C%22%3A%22181%22%2C%22Desc_Sulfur_C%22%3A%2260%22%2C%22Desc_OreBauxite_C%22%3A%22148%22%2C%22Desc_IronIngot_C%22%3A%22214%22%2C%22Desc_Plastic_C%22%3A%2211%22%2C%22Desc_Rubber_C%22%3A%2290%22%7D%2C%22direction%22%3A%22DOWN%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_AdheredIronPlate_C%22%2C%22Recipe_Alternate_InstantScrap_C%22%2C%22Recipe_Alternate_Computer_2_C%22%2C%22Recipe_Alternate_CrystalOscillator_C%22%2C%22Recipe_Alternate_HeatSink_1_C%22%2C%22Recipe_Alternate_ModularFrameHeavy_C%22%2C%22Recipe_Alternate_IngotSteel_1_C%22%2C%22Recipe_Alternate_EncasedIndustrialBeam_C%22%2C%22Recipe_Alternate_Screw_2_C%22%2C%22Recipe_Alternate_Wire_1_C%22%5D%7D

**Comment by AnthorNet** [comment]
Yes thanks, I agree something looks wrong.

**Comment by Slayerfroggie** [comment]
also getting this same issue here 
![image](https://user-images.githubusercontent.com/47513385/128285312-ba6e9892-2028-4b29-9416-1692cfc97892.png)
