### ISSUE TITLE
Saved link (bookmark) no longer brings up production workflow

### ISSUE THREAD

**Issue by Alcasan** [AnthorNet/SC-ProductionPlanner#28]
I have saved some productions as bookmarks, which used to work when I clicked on them, but now it just brings up a blank production page. I've tried different browsers and without any extension etc installed but am getting the same issue on all of them. Is it just me or is everyone experiencing this?

When I paste this link into a new window, I only get the Uranium Waste from the "input" section showing.

https://satisfactory-calculator.com/en/production-planner/index/index/json/%7B%22Desc_PlutoniumFuelRod_C%22%3A%22.5%22%2C%22input%22%3A%7B%22Desc_NuclearWaste_C%22%3A%22100%22%7D%2C%22view%22%3A%22SIMPLE%22%2C%22altRecipes%22%3A%5B%22Recipe_PureAluminumIngot_C%22%2C%22Recipe_Alternate_FertileUranium_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%5D%7D

**Comment by Alcasan** [comment]
Link would probable help to test. When I paste this link into a new window, I only get the Uranium Waste from the "input" section showing.

https://satisfactory-calculator.com/en/production-planner/index/index/json/%7B%22Desc_PlutoniumFuelRod_C%22%3A%22.5%22%2C%22input%22%3A%7B%22Desc_NuclearWaste_C%22%3A%22100%22%7D%2C%22view%22%3A%22SIMPLE%22%2C%22altRecipes%22%3A%5B%22Recipe_PureAluminumIngot_C%22%2C%22Recipe_Alternate_FertileUranium_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%5D%7D

**Comment by AnthorNet** [comment]
0.5 float was the problem. It should be fixed.

**Comment by Alcasan** [comment]
Thank you!
