### ISSUE TITLE
feature request: production planner for mods

### ISSUE THREAD

**Issue by boneskull** [AnthorNet/SC-ProductionPlanner#30]
Specifically, looking at the [More Milestones +100](https://ficsit.app/mod/CYKiwTGyi6cxTY) mod.

I'll probably clone the repo and see how tough this would be to do myself.  Would you be interested in a PR to add this, or not?

**Comment by AnthorNet** [comment]
Mod author need to fill the backend, but it's already a thing on the production planner.
