### ISSUE TITLE
Add residual recipes to alternate recipes

### ISSUE THREAD

**Issue by andocromn** [AnthorNet/SC-ProductionPlanner#35]
Although these are technically stock recipes it would be useful to be able to select them as a part of mid stage refinement processes

- residual fuel
- residual rubber
- residual plastic

example of workaround with imperfect numbers

https://satisfactory-calculator.com/en/production-planner/index/index/json/{"Desc_LiquidFuel_C":"1","Desc_LiquidTurboFuel_C":"598","view":"SIMPLE","altRecipes":["Recipe_ResidualFuel_C","Recipe_Alternate_TurboBlendFuel_C","Recipe_Alternate_HeavyOilResidue_C"]}

**Comment by AnthorNet** [comment]
You should normally be able to select them in options > Alternate recipe?
