### ISSUE TITLE
[Feature Request] - Button to maximize the output

### ISSUE THREAD

**Issue by Gamemap** [AnthorNet/SC-ProductionPlanner#36]
Perhaps you could add a button to maximize the output (if possible to 100%) with almost the same number of buildings. Currently, you can only try to change the output number or calculate it yourself.

Before optimizing:
https://satisfactory-calculator.com/de/production-planner/index/index/json/%7B%22Desc_Stone_C%22%3A%22400%22%7D
![Satisfactory_1](https://user-images.githubusercontent.com/71942164/137684305-e07ac066-01db-4834-9ea7-5622279e9951.PNG)

After optimization:
https://satisfactory-calculator.com/de/production-planner/index/index/json/%7B%22Desc_Stone_C%22%3A%22600%22%7D
![Satisfactory_2](https://user-images.githubusercontent.com/71942164/137684313-34175ef3-95db-4001-9623-6675f084fc37.PNG)

**Comment by Allread** [comment]
Need this !

**Comment by MBascuhadar** [comment]
Is there a chance this can be implemented?
