### ISSUE TITLE
[Feature Request] Option to specify multiple available miner quality types

### ISSUE THREAD

**Issue by RyanMcCall** [AnthorNet/SC-ProductionPlanner#37]
From what I see right now, you can only pick one miner mk. # with a corresponding quality and the production planner uses this to plan its build. It would be nice to be able to add multiple quality types and the quantity. This way if you have 3 normal ore sites and then come across a pure one you can tell the planner that you have these available and it can make best use of each.

**Comment by drachs** [comment]
How do you select the miner type and ore quality?
