### ISSUE TITLE
Wrong aggregations with multiple item outputs varying depending on selected language

### ISSUE THREAD

**Issue by addy90** [AnthorNet/SC-ProductionPlanner#41]
Thanks for your great tool for satisfactory. I have a strange aggregation issue when using German language.

In the following link, "Rubber" which is named "Gummi" is said to be 430 units/s in the items tab, but in the graph we can see that beside of the 430 units/s there is another 20 units/s line. Correctly it should be 450 units/s. Moreover the "Heavy Oil Residue" which in German is "Schwerölrückstände" has a similar issue but here there are shown 20 m³/s on the graph and many side lines and on the item tab there are shown 450,02 m³/s but correctly it would be 450 m³/s. Still in the latter case of heavy oil residue the data on the items tab is nearer to the correct value than with rubber.

The German link that shows this behavior: [German link](https://satisfactory-calculator.com/de/planners/production/index/json/%7B%22Desc_LiquidTurboFuel_C%22%3A%22319.84375%22%2C%22Desc_MotorLightweight_C%22%3A%229.375%22%2C%22Desc_TurboFuel_C%22%3A%2220%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_TurboBlendFuel_C%22%2C%22Recipe_Alternate_CoatedIronCanister_C%22%2C%22Recipe_Alternate_CokeSteelIngot_C%22%2C%22Recipe_Alternate_ElectrodeCircuitBoard_C%22%2C%22Recipe_Alternate_PureCopperIngot_C%22%2C%22Recipe_Alternate_PureIronIngot_C%22%2C%22Recipe_Alternate_PureQuartzCrystal_C%22%2C%22Recipe_Alternate_SteamedCopperSheet_C%22%2C%22Recipe_Alternate_DilutedFuel_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%2C%22Recipe_Alternate_Computer_2_C%22%2C%22Recipe_Alternate_Motor_1_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_2_C%22%2C%22Recipe_Alternate_Rotor_C%22%5D%7D)

In the English version with the exact same recipe, rubber is correct with 450 units/s but now the heavy oil residue is completely bugged producing nearly 640 units/s unnecessary plastic: [English link](https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_LiquidTurboFuel_C%22%3A%22319.84375%22%2C%22Desc_MotorLightweight_C%22%3A%229.375%22%2C%22Desc_TurboFuel_C%22%3A%2220%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_TurboBlendFuel_C%22%2C%22Recipe_Alternate_CoatedIronCanister_C%22%2C%22Recipe_Alternate_CokeSteelIngot_C%22%2C%22Recipe_Alternate_ElectrodeCircuitBoard_C%22%2C%22Recipe_Alternate_PureCopperIngot_C%22%2C%22Recipe_Alternate_PureIronIngot_C%22%2C%22Recipe_Alternate_PureQuartzCrystal_C%22%2C%22Recipe_Alternate_SteamedCopperSheet_C%22%2C%22Recipe_Alternate_DilutedFuel_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%2C%22Recipe_Alternate_Computer_2_C%22%2C%22Recipe_Alternate_Motor_1_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_2_C%22%2C%22Recipe_Alternate_Rotor_C%22%5D%7D)

When I remove the "Packaged Turbofuel" or "Abgefüllter Turbotreibstoff" and increase the "Turbo fuel" by 20 m³/s then both recipes work correctly except that the mentioned item is missing.

German link with no Packaged Turbofuel shows correct rubber (Gummi) and Heavy Oil Residue (Schwerölrückstände): [German link without Packaged Turbofuel](https://satisfactory-calculator.com/de/planners/production/index/json/%7B%22Desc_LiquidTurboFuel_C%22%3A%22339.84375%22%2C%22Desc_MotorLightweight_C%22%3A%229.375%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_TurboBlendFuel_C%22%2C%22Recipe_Alternate_CoatedIronCanister_C%22%2C%22Recipe_Alternate_CokeSteelIngot_C%22%2C%22Recipe_Alternate_ElectrodeCircuitBoard_C%22%2C%22Recipe_Alternate_PureCopperIngot_C%22%2C%22Recipe_Alternate_PureIronIngot_C%22%2C%22Recipe_Alternate_PureQuartzCrystal_C%22%2C%22Recipe_Alternate_SteamedCopperSheet_C%22%2C%22Recipe_Alternate_DilutedFuel_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%2C%22Recipe_Alternate_Computer_2_C%22%2C%22Recipe_Alternate_Motor_1_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_2_C%22%2C%22Recipe_Alternate_Rotor_C%22%5D%7D)
When switching to English the magical plasic reappears: [English link without Packaged Turbofuel](https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_LiquidTurboFuel_C%22%3A%22339.84375%22%2C%22Desc_MotorLightweight_C%22%3A%229.375%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_TurboBlendFuel_C%22%2C%22Recipe_Alternate_CoatedIronCanister_C%22%2C%22Recipe_Alternate_CokeSteelIngot_C%22%2C%22Recipe_Alternate_ElectrodeCircuitBoard_C%22%2C%22Recipe_Alternate_PureCopperIngot_C%22%2C%22Recipe_Alternate_PureIronIngot_C%22%2C%22Recipe_Alternate_PureQuartzCrystal_C%22%2C%22Recipe_Alternate_SteamedCopperSheet_C%22%2C%22Recipe_Alternate_DilutedFuel_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%2C%22Recipe_Alternate_Computer_2_C%22%2C%22Recipe_Alternate_Motor_1_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_2_C%22%2C%22Recipe_Alternate_Rotor_C%22%5D%7D)

Only when removing the Turbo Fuel, too, the recipes are correct in both cases.
See German link with only Turbo Motors (Turbomotoren): [German Turbo Motors](https://satisfactory-calculator.com/de/planners/production/index/json/%7B%22Desc_MotorLightweight_C%22%3A%229.375%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_CoatedIronCanister_C%22%2C%22Recipe_Alternate_CokeSteelIngot_C%22%2C%22Recipe_Alternate_ElectrodeCircuitBoard_C%22%2C%22Recipe_Alternate_PureCopperIngot_C%22%2C%22Recipe_Alternate_PureIronIngot_C%22%2C%22Recipe_Alternate_PureQuartzCrystal_C%22%2C%22Recipe_Alternate_SteamedCopperSheet_C%22%2C%22Recipe_Alternate_DilutedFuel_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%2C%22Recipe_Alternate_TurboBlendFuel_C%22%2C%22Recipe_Alternate_Computer_2_C%22%2C%22Recipe_Alternate_Motor_1_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_2_C%22%2C%22Recipe_Alternate_Rotor_C%22%5D%7D)
And English version: [English Turbo Motors](https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_MotorLightweight_C%22%3A%229.375%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_CoatedIronCanister_C%22%2C%22Recipe_Alternate_CokeSteelIngot_C%22%2C%22Recipe_Alternate_ElectrodeCircuitBoard_C%22%2C%22Recipe_Alternate_PureCopperIngot_C%22%2C%22Recipe_Alternate_PureIronIngot_C%22%2C%22Recipe_Alternate_PureQuartzCrystal_C%22%2C%22Recipe_Alternate_SteamedCopperSheet_C%22%2C%22Recipe_Alternate_DilutedFuel_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%2C%22Recipe_Alternate_TurboBlendFuel_C%22%2C%22Recipe_Alternate_Computer_2_C%22%2C%22Recipe_Alternate_Motor_1_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_2_C%22%2C%22Recipe_Alternate_Rotor_C%22%5D%7D)

So to conclude, I wanted to make use of the unused Heavy Oil Residue that I receive with my Turbo Motor recipe but this lead to the described errors. Thank you for investigating and have a good day!

**Comment by AnthorNet** [comment]
Will try to find where the problem is

**Comment by addy90** [comment]
The problem with varying results in different languages definitely disappeared, thanks for your quick response for that!
The problem with the Heavy Oil Residue not being reused for the Turbo Fuel, however now also happens in German. Before the fix in German it was reused correctly and no plastic was produced, now in both languages the plasic is wrongly added. So the fix had a side effect, unfortunately, and the behavior in German for the second link was correct before. But at least rubber is now correct in all cases, which was not the case before.
