### ISSUE TITLE
[Feature Request] Being able to add mod (recipe, resource, building) to the production planner

### ISSUE THREAD

**Issue by zoqin** [AnthorNet/SC-ProductionPlanner#45]
Hello, I hope you are doing great

I think it would be great to add mod to the production planner, as modder already add their resource to the index of SC

Thanks in advance to consider the feature, have a nice day

**Comment by AnthorNet** [comment]
On the mods pages, you can click the icon to get the planner loads a specific mod. 
I'll try to add another select like the alternate one to enable mods on the fly.

**Comment by AnthorNet** [comment]
Here's an example: https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_FM_DoggoChow_C%22%3A3%2C%22mods%22%3A%5B%224%22%5D%7D
