### ISSUE TITLE
Partial merging broken.

### ISSUE THREAD

**Issue by MdBourg98** [AnthorNet/SC-ProductionPlanner#5]
![image](https://user-images.githubusercontent.com/57682576/104950897-87e41800-598f-11eb-8ed9-ae70cd5b7e3a.png)
![image](https://user-images.githubusercontent.com/57682576/104951072-dc879300-598f-11eb-8114-7454a15b90e8.png)
![image](https://user-images.githubusercontent.com/57682576/104951090-e4473780-598f-11eb-8cda-149cbd03e7c6.png)
![image](https://user-images.githubusercontent.com/57682576/104951116-f032f980-598f-11eb-8205-38e557665ca8.png)
![image](https://user-images.githubusercontent.com/57682576/104951143-fd4fe880-598f-11eb-998a-058c5c529d8a.png)

Mergers and splitters are in odd places and use weird numbers. buildings showing up without input and output lines. Mergers with 1 input. Input and output of machines not matching with efficiency and production ratios.

**Comment by AnthorNet** [comment]
Canal you share the link please?

**Comment by MdBourg98** [comment]
Sorry about that, I meant to add it but got sidetracked.

https://satisfactory-calculator.com/en/production-planner/index/index/Desc_IronPlateReinforced_C/10/direction/RIGHT/maxBeltSpeed/120/minerSpeed/1;pure

**Comment by Edeyz** [comment]
I'm having similar issues, it seems to be associated with the 're-use buildings' setting.

Note that in my example all the ore quantity are messed up.


https://satisfactory-calculator.com/en/production-planner/index/index/Desc_Computer_C/1/direction/RIGHT/maxBeltSpeed/60/minerSpeed/3;impure/pumpSpeed/1;pure/altRecipes/Recipe_Alternate_PureCopperIngot_C/altRecipes/Recipe_Alternate_PureIronIngot_C/altRecipes/Recipe_Alternate_PureQuartzCrystal_C/altRecipes/Recipe_Alternate_CircuitBoard_1_C/altRecipes/Recipe_Alternate_Computer_2_C/altRecipes/Recipe_Alternate_ReinforcedIronPlate_1_C/altRecipes/Recipe_Alternate_Screw_C

**Comment by AnthorNet** [comment]
Thanks for the report!
I'll revert back the partial merging code introduced to handle overclocking tomorrow morning!

Need to review that copy :)

**Comment by rdc74656** [comment]
I’m having an issue where it’s trying to have 3 inputs going into an assembler.

**Comment by AnthorNet** [comment]
Hard to help you without more details, but please open your own issue.

**Comment by AnthorNet** [comment]
@rdc74656 See: https://github.com/AnthorNet/SC-ProductionPlanner/issues/9
