### ISSUE TITLE
[Feature Request] Download/Upload Production Plans

### ISSUE THREAD

**Issue by richardhensley** [AnthorNet/SC-ProductionPlanner#50]
Have you considered being able to save and load production plans? 

Use Case/Workflow
1. Make a paper design
2. Make a set of production plans to "do the math" 
3. Make a blueprint

What I would like to do is save the production plans that support the blueprint so that I can tweak the production plans later, and know what changes I should make in my blueprint.

Right now, I solve this problem by saving a screen shot of the network graph along with blueprint documentation in a google doc. When I want to tweak it, I recreate the production plan in production planner based on the network graph picture.

**Comment by PeKino-308** [comment]
While the feature is not avail/under progress, simply copy and save the URL and you can load it anytime.
