### ISSUE TITLE
[Feature Request] More Building Use Details on Simple View

### ISSUE THREAD

**Issue by richardhensley** [AnthorNet/SC-ProductionPlanner#51]
Quite often when planning I would like to know more granularity than 3.9 Constructors, I would like to know that it is actually 3.87 or 387%. 

Right now, to get that level of detail, I use the following workflow:

1. Create my production plan in simple view
2. Validate the production plan
3. Change the production plan to realistic view
4. Move the graph around so that all the buildings producing the same item are together
5. Add up the total percentage
6. Now I have the number above at the granularity I would like

Thanks for making such a great tool. You have my support until I stop playing the game.

**Comment by AnthorNet** [comment]
I believe it should be the case now
