### ISSUE TITLE
Plastic calculation is wrong in simple mode

### ISSUE THREAD

**Issue by KreizIT** [AnthorNet/SC-ProductionPlanner#52]
Hi,

For a battery planning, simple mode give 14 units of plastic but reality and realistic mode give right answer 300 units/min.

Simple mode :
https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_Battery_C%22%3A%22150%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_ClassicBattery_C%22%2C%22Recipe_ResidualFuel_C%22%2C%22Recipe_ResidualRubber_C%22%2C%22Recipe_Alternate_CopperAlloyIngot_C%22%2C%22Recipe_Alternate_DilutedPackagedFuel_C%22%2C%22Recipe_Alternate_ElectroAluminumScrap_C%22%2C%22Recipe_Alternate_FusedWire_C%22%2C%22Recipe_PureAluminumIngot_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%5D%7D

Realistic : 
https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22view%22%3A%22REALISTIC%22%2C%22maxBeltSpeed%22%3A%22780%22%2C%22maxPipeSpeed%22%3A%22600000%22%2C%22Desc_Battery_C%22%3A%22150%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_ClassicBattery_C%22%2C%22Recipe_ResidualFuel_C%22%2C%22Recipe_ResidualRubber_C%22%2C%22Recipe_Alternate_CopperAlloyIngot_C%22%2C%22Recipe_Alternate_DilutedPackagedFuel_C%22%2C%22Recipe_Alternate_ElectroAluminumScrap_C%22%2C%22Recipe_Alternate_FusedWire_C%22%2C%22Recipe_PureAluminumIngot_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%5D%7D

PS : Thank you very much for your great job by the way 😃

**Comment by AnthorNet** [comment]
I could not reproduce it, I get 300 from the simple view for plastic.

**Comment by AnthorNet** [comment]
I'll run some test on Firefox later.

**Comment by AnthorNet** [comment]
Seems like on Firefox it sues another alternate recipe and uses Plastic by product, plus another 286 plastic, so it's fine, but it should be constant on all browsers.
