### ISSUE TITLE
[Feature Request] Allow production planner to pull in alternate recipes from savefile

### ISSUE THREAD

**Issue by dsarmiento** [AnthorNet/SC-ProductionPlanner#56]
Using the save file either uploaded to the interactive map or can be re-uploaded to the production planner. To auto-magically fill out the alternate recipes the user has unlocked.

**Comment by gyles19** [comment]
I would really like this one, myself.  We don't have all the alts unlocked yet, and producing the best possible fuel for what we currently have available is daunting.  Turbofuel alts, fuel alts, heavy oil reside alts, packager, blender, compact coal vs petroleum coke, rubber alts... its spaghetti at its finest.

**Comment by AnthorNet** [comment]
I knoooowwwww!
Trust me, love will be given soon after 1.0 to the planner. :)

**Comment by AnthorNet** [comment]
Done!
Right now the schematics are only populated when you visit the Research > Alternate Recipes on SCIM, but once the next update is out it will be populated once you load a save.
