### ISSUE TITLE
Required buildings count is Almost correct.

### ISSUE THREAD

**Issue by quest5m** [AnthorNet/SC-ProductionPlanner#60]
Planner > Production Planner > Buildings Tab
ITEM: Thermal Propulsion Rocket

A production machine can only produce 1 recipe at a time.
The planner should take into account the number of different recipes that are required to produce a final item.

Per the link below, 1.833x blenders are needed.
Mathematically, this is correct.

However, there are 2 different recipes being produced
- Fused Modular Frame, and
- Cooling System.

So a minimum of 2 blenders would be needed.
This would also change the amount of materials needed to create the initial Buildings.

ref:
eg: Blenders - 2 recipes require a minimum of 2 blenders.
https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_SpaceElevatorPart_8_C%22%3A%221%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_HeatSink_1_C%22%5D%7D

**Comment by C80** [comment]
Also, i don't need to know what the materials would be for 1.833x blenders, or 78.164x Constructors... I will build 2 and 84, respectively.
