### ISSUE TITLE
Heavy Oil Residue and Polymer Resin alternate recipe splits refineries for no reason in simple view mode

### ISSUE THREAD

**Issue by Matt249** [AnthorNet/SC-ProductionPlanner#62]
It's hard to describe, but the screenshot is self-explanatory, instead of being one node they are split in two with one at a very low rate.
I was calculating production for 300 batteries per min. with all alternate recipes.
Maybe this is due to the overproduction of one byproduct, so it could be solved by adding an option to try to get rid of the byproduct excess.
![image](https://github.com/AnthorNet/SC-ProductionPlanner/assets/16977040/aa54773a-9db5-456d-b0cf-d1d3446ca659)

**Comment by Arkonos** [comment]
Same issue here. In addition, it has me creating 3,846.889 Polymer Resin, but only uses 1788.75 of it.

https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_ModularFrameHeavy_C%22%3A%2215%22%2C%22Desc_CircuitBoard_C%22%3A%2215%22%2C%22Desc_Computer_C%22%3A%2215%22%2C%22Desc_SpaceElevatorPart_3_C%22%3A%2215%22%2C%22Desc_SpaceElevatorPart_5_C%22%3A%2210%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_ModularFrameHeavy_C%22%2C%22Recipe_Alternate_ElectrodeCircuitBoard_C%22%2C%22Recipe_Alternate_Computer_2_C%22%2C%22Recipe_Alternate_HighSpeedWiring_C%22%2C%22Recipe_ResidualFuel_C%22%2C%22Recipe_ResidualPlastic_C%22%2C%22Recipe_ResidualRubber_C%22%2C%22Recipe_Alternate_Coal_1_C%22%2C%22Recipe_Alternate_Coal_2_C%22%2C%22Recipe_Alternate_WetConcrete_C%22%2C%22Recipe_Alternate_TurboHeavyFuel_C%22%2C%22Recipe_Alternate_SteelRod_C%22%2C%22Recipe_Alternate_SteelCanister_C%22%2C%22Recipe_Alternate_SteamedCopperSheet_C%22%2C%22Recipe_Alternate_RubberConcrete_C%22%2C%22Recipe_Alternate_RecycledRubber_C%22%2C%22Recipe_Alternate_PureQuartzCrystal_C%22%2C%22Recipe_Alternate_PureIronIngot_C%22%2C%22Recipe_Alternate_PureCopperIngot_C%22%2C%22Recipe_Alternate_PureCateriumIngot_C%22%2C%22Recipe_PureAluminumIngot_C%22%2C%22Recipe_Alternate_PolymerResin_C%22%2C%22Recipe_Alternate_PlasticSmartPlating_C%22%2C%22Recipe_Alternate_HeavyOilResidue_C%22%2C%22Recipe_Alternate_FusedWire_C%22%2C%22Recipe_Alternate_FlexibleFramework_C%22%2C%22Recipe_Alternate_ElectroAluminumScrap_C%22%2C%22Recipe_Alternate_DilutedPackagedFuel_C%22%2C%22Recipe_Alternate_CopperRotor_C%22%2C%22Recipe_Alternate_CopperAlloyIngot_C%22%2C%22Recipe_Alternate_CokeSteelIngot_C%22%2C%22Recipe_Alternate_CoatedIronPlate_C%22%2C%22Recipe_Alternate_CoatedIronCanister_C%22%2C%22Recipe_Alternate_CoatedCable_C%22%2C%22Recipe_Alternate_BoltedFrame_C%22%2C%22Recipe_Alternate_AdheredIronPlate_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%2C%22Recipe_Alternate_AutomatedMiner_C%22%2C%22Recipe_Alternate_AlcladCasing_C%22%2C%22Recipe_Alternate_SteelPipe_Molded_C%22%2C%22Recipe_Alternate_SteelPipe_Iron_C%22%2C%22Recipe_Alternate_SteelCastedPlate_C%22%2C%22Recipe_Alternate_SteelBeam_Molded_C%22%2C%22Recipe_Alternate_AluminumRod_C%22%2C%22Recipe_Alternate_AILimiter_Plastic_C%22%2C%22Recipe_Alternate_Quartz_Fused_C%22%2C%22Recipe_Alternate_IronIngot_Basic_C%22%2C%22Recipe_Alternate_CopperIngot_Tempered_C%22%2C%22Recipe_Alternate_CateriumIngot_Tempered_C%22%2C%22Recipe_Alternate_Wire_2_C%22%2C%22Recipe_Alternate_Wire_1_C%22%2C%22Recipe_Alternate_Stator_C%22%2C%22Recipe_Alternate_Silica_C%22%2C%22Recipe_Alternate_Screw_2_C%22%2C%22Recipe_Alternate_Screw_C%22%2C%22Recipe_Alternate_Rotor_C%22%2C%22Recipe_Alternate_EncasedIndustrialBeam_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_2_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_1_C%22%2C%22Recipe_Alternate_Quickwire_C%22%2C%22Recipe_Alternate_Plastic_1_C%22%2C%22Recipe_Alternate_Motor_1_C%22%2C%22Recipe_Alternate_ModularFrame_C%22%2C%22Recipe_Alternate_IngotSteel_2_C%22%2C%22Recipe_Alternate_IngotSteel_1_C%22%2C%22Recipe_Alternate_IngotIron_C%22%2C%22Recipe_Alternate_HighSpeedConnector_C%22%2C%22Recipe_Alternate_Gunpowder_1_C%22%2C%22Recipe_Alternate_CrystalOscillator_C%22%2C%22Recipe_Alternate_Concrete_C%22%2C%22Recipe_Alternate_Computer_1_C%22%2C%22Recipe_Alternate_CircuitBoard_2_C%22%2C%22Recipe_Alternate_Cable_2_C%22%2C%22Recipe_Alternate_Cable_1_C%22%5D%7D
