### ISSUE TITLE
Power Planner is wrong with overclocking

### ISSUE THREAD

**Issue by dcelasun** [AnthorNet/SC-ProductionPlanner#65]
18 uranium fuel rods per minute can feed 90 nuclear power plants at 100% clock speed.

Since power generators scale linearly, that should be cut down to 90*100/250=36 power plants at 250%. But the planner shows 45:

![image](https://github.com/AnthorNet/SC-ProductionPlanner/assets/144373/49c7faf6-5f5c-4ed9-9fba-c41abbdaaa14)

**Comment by AnthorNet** [comment]
fixed, thanks for reporting it :)

**Comment by dcelasun** [comment]
> fixed, thanks for reporting it :)

Nice work, but I don't think it's fully fixed yet. The power plant count is correct now (36) but the uranium rods are wrong. It says 14.4, but that should be 18 since a nuclear power plant at 250% burns 0.5 uranium rods per minute.

![image](https://github.com/AnthorNet/SC-ProductionPlanner/assets/144373/8a15d03f-8076-4776-867e-126b91de9e69)

**Comment by AnthorNet** [comment]
Double fixed :p

**Comment by dcelasun** [comment]
Now it looks perfect :)
