### ISSUE TITLE
1.0 new formulas are having some weird issues

### ISSUE THREAD

**Issue by mingl0280** [AnthorNet/SC-ProductionPlanner#67]
Game branch selection: stable.

Issue:
Ionized fuel and SAM-related formulas are invalid.
For example:
![image](https://github.com/user-attachments/assets/2c5df6ba-1767-4bfc-901d-dbf5fc8bc162)

Correct result:
![image](https://github.com/user-attachments/assets/864653ad-967c-465f-ab56-2cd5cc15df1b)
![image](https://github.com/user-attachments/assets/2b85bc67-9337-4979-b06c-46516f522ec6)

It seems like the items were just not linked together nor resolved properly.

**Comment by AnthorNet** [comment]
Should be fixed
