### ISSUE TITLE
Plastic AI Limiter Output Incorrect

### ISSUE THREAD

**Issue by Bgilliam42** [AnthorNet/SC-ProductionPlanner#69]
The Plastic AI limiter at 100% utilization in the planner says it will output 6 units/m. While the official wiki and in-game are 8 units/m. The input values are correct though, so it just needs to be updated on the output side so that it calculates things properly down the chain.

**Comment by AnthorNet** [comment]
What do you mean by 100% utilization? 
Please share the link as the recipe seems correct in SCIM.

![image](https://github.com/user-attachments/assets/1af67592-45f9-4a3f-a752-845fe552af33)

**Comment by Bgilliam42** [comment]
Apologies. Not a frequent Github user, so didn't see your initial reply. At first I didn't even realize it was URL based, to share recipes, so I didn't capture it at the time or take a screenshot. At the time, I double checked it by using an additional recipe and it was wrong there too. I've since went back and looked in my history and checked every production planner URL found from that date. They all show correctly now, so I can't explain what happened at the time.

**Comment by AnthorNet** [comment]
No problem, could just be some cache issue.
