### ISSUE TITLE
Missing Item: Alien Power Matrix

### ISSUE THREAD

**Issue by ryan-skabelund** [AnthorNet/SC-ProductionPlanner#70]
In the Production Planner, `Alien Power Matrix` is currently missing as a listed item. The item can be found here:
https://satisfactory.wiki.gg/wiki/Alien_Power_Matrix

I've ensured I'm on the stable branch and have noticed this over the past few days as I've been planning out my end game factories.

Let me know if you have any questions or need anything else from me. Appreciate your hard work and amazing tool!

**Comment by AnthorNet** [comment]
Missed it!
Should be fixed: https://satisfactory-calculator.com/en/items/detail/id/Desc_AlienPowerFuel_C/name/Alien+Power+Matrix

Can take time to regenerate data but it's in now :)
