### ISSUE TITLE
Add New fuel types to Power planner

### ISSUE THREAD

**Issue by Frozen8950** [AnthorNet/SC-ProductionPlanner#71]
Is it possible to add new fuel types to the Power planner? I want to build a rocket fuel factory, but math is hard.
Rocket Fuel, Ionized Fuel, and Ficsonium Fuel Rod is missing.

**Comment by AnthorNet** [comment]
Both fuel are in gas, and the rod in nuclear

**Comment by AnthorNet** [comment]
Sorry I wasn't on the Power Planner! Fixed now :)

**Comment by Frozen8950** [comment]
Thanks! I see them now, however I think the calculation might be off.

If I say I need 250mw, it correctly tells me I need 1 machine. However it
says I need 4,166 fuel per min. It's impossible to put that much fuel into
a machine with the 600 Mk2 Pipes.
Is it supposed to be 4.166?
