### ISSUE TITLE
Dissovled Silica does not bring up a production map when selected as desired output.

### ISSUE THREAD

**Issue by DrakeFS** [AnthorNet/SC-ProductionPlanner#72]
![SC-Missing diagram](https://github.com/user-attachments/assets/fab359d5-ca58-4af2-84a2-97a50597770b)

Dissolved Silica does not show its network graph\tree list\items\buildings.  Anything that requires Dissolved Silica will just show the item (as if you added it in the input tab).

Quartz however works correctly when selecting the alternate recipe "Quartz Purification".  Once it has loaded the network graph this way, it works correctly for dissolved silica as well.

**Comment by AnthorNet** [comment]
There is no recipe available until you tick the Quartz Purification alternate recipe :)

**Comment by AnthorNet** [comment]
Alternate recipe will now be selected when choosing it
