### ISSUE TITLE
Assembly Director System Recipe Incorrect

### ISSUE THREAD

**Issue by NathanGilbert2** [AnthorNet/SC-ProductionPlanner#75]
The Assembly Director System (ADS) requires 1.5 Adaptive Control Units (ACU) per min and 0.75 Supercomputers per min normally in game. The site is showing 2 ACU and 1 Supercomputer throwing off the calculation of the planner.

[ADS](https://satisfactory-calculator.com/en/items/detail/id/Desc_SpaceElevatorPart_7_C/name/Assembly+Director+System)

[ADS production planner](https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_SpaceElevatorPart_7_C%22%3A%222.5%22%2C%22input%22%3A%7B%22Desc_Plastic_C%22%3A%2290%22%7D%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_WetConcrete_C%22%2C%22Recipe_Alternate_SteamedCopperSheet_C%22%2C%22Recipe_Alternate_PureIronIngot_C%22%2C%22Recipe_Alternate_SteelPipe_Molded_C%22%2C%22Recipe_Alternate_SteelBeam_Molded_C%22%2C%22Recipe_Alternate_Wire_1_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_2_C%22%2C%22Recipe_Alternate_IngotSteel_1_C%22%2C%22Recipe_Alternate_ModularFrameHeavy_C%22%5D%7D)

**Comment by AnthorNet** [comment]
Values are correct, output is 0.75 per minute, not 1

**Comment by NathanGilbert2** [comment]
> Values are correct, output is 0.75 per minute, not 1

You are right, was looking at the amount and not the rate on the site. My bad.

Though, I am still confused about this math:
![image](https://github.com/user-attachments/assets/95968c11-af09-4edf-9907-aedcc91dcba7)

I should only need 5 ACU for 2.5 ADS.

**Comment by AnthorNet** [comment]
Odd, using your link I get the correct math!
![image](https://github.com/user-attachments/assets/41d2d1b7-5971-402e-acbc-32fe04b1a108)

**Comment by NathanGilbert2** [comment]
Looks like if I open a private browser it works correctly. Might have got into a funny state with this particular tab. Opening in a new tab also works, but if I refresh the weird tab one it maintains its state. For fun, here is the console output and a HAR from the broken tab. You might find something insightful from it, but from my end I would consider this resolved. Appreciate your quick response!
[satisfactory-calculator.com_Archive [24-10-01 06-21-00].txt](https://github.com/user-attachments/files/17203498/satisfactory-calculator.com_Archive.24-10-01.06-21-00.txt)
[console-export-2024-10-1_6-20-36.txt](https://github.com/user-attachments/files/17203500/console-export-2024-10-1_6-20-36.txt)

**Comment by AnthorNet** [comment]
We'll leave it as an odd cache issue ;D
