### ISSUE TITLE
iOS app 

### ISSUE THREAD

**Issue by rdc74656** [AnthorNet/SC-ProductionPlanner#8]
Could I ask for the production planner to be created into an iOS app, maybe even android?  I’m currently having to use iPhone as I don’t have multi-monitors and just thought would be nice.  Can’t seem to be able to tap on anything in the “add an item” option when using iPad, only brings up the description of the part tapped.
Thanks

**Comment by AnthorNet** [comment]
Sadly will not be able to to do that :)
