### ISSUE TITLE
[Bug] Combined Heavy Oil from Plastic and Rubber processing is treated separately

### ISSUE THREAD

**Issue by Pepek94** [AnthorNet/SC-ProductionPlanner#84]
Hello. 
[Link to SCPP](https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_LiquidFuel_C%22%3A%22680%22%2C%22Desc_Plastic_C%22%3A%22680%22%2C%22Desc_Rubber_C%22%3A%22680%22%2C%22input%22%3A%7B%22Desc_Coal_C%22%3A%22960%22%2C%22Desc_Sulfur_C%22%3A%22480%22%2C%22Desc_LiquidOil_C%22%3A%222040%22%7D%2C%22altRecipes%22%3A[%22Recipe_ResidualFuel_C%22]%7D)

I tried to create the best possible oil production plan, I want to have 480 plastic and rubber, and use all the heavy oil as fuel. I tried to add new production as fuel, but the heavy oil is not added up (plstic and rubber) making the Planner want to force new oil deposits from me :X

**Comment by davemsh** [comment]
I've just noticed this occurring for me as well.
[Example](https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_RocketFuel_C%22%3A%22400%22%2C%22Desc_Plastic_C%22%3A%22200%22%2C%22Desc_Rubber_C%22%3A%22200%22%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_RocketFuel_Nitro_C%22%2C%22Recipe_ResidualFuel_C%22%2C%22Recipe_Alternate_ElectrodeCircuitBoard_C%22%2C%22Recipe_Alternate_PolyesterFabric_C%22%5D%7D)

**Comment by AnthorNet** [comment]
Should be fixed!
Before:
![image](https://github.com/user-attachments/assets/7cf3359a-a219-453c-a088-44eabb892f54)

After:
![image](https://github.com/user-attachments/assets/b3ebbe92-a5db-48a3-8141-bce6fd440c22)
