### ISSUE TITLE
Quantum Computers Not Showing

### ISSUE THREAD

**Issue by BigMac0815** [AnthorNet/SC-ProductionPlanner#88]
When I tell the website to show me the quantum computer crafting tree it doesn't show up, but it seems to be JUST the quantum computer.

Here's a link for just the quantum computer:
https://satisfactory-calculator.com/en/planners/production/index/json/%7B"Desc_ComputerQuantum_C"%3A"1"%7D

And When combined with other outputs:
https://satisfactory-calculator.com/en/planners/production/index/json/%7B"Desc_Battery_C"%3A"10"%2C"Desc_ComputerQuantum_C"%3A"1"%7D

**Comment by AnthorNet** [comment]
Item was removed in game in favor of Super Computer.
