### ISSUE TITLE
[Bug] Unnecessary Dark Matter Residue production

### ISSUE THREAD

**Issue by Loyalar** [AnthorNet/SC-ProductionPlanner#92]
Making a rather complex setup of T9 space elevator parts got me to this production planner:

[Link to production planner](https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_SpaceElevatorPart_11_C%22%3A%222%22%2C%22Desc_SpaceElevatorPart_12_C%22%3A%226%22%2C%22input%22%3A%7B%22Desc_AluminumPlate_C%22%3A%2290%22%2C%22Desc_FicsiteMesh_C%22%3A%2290%22%2C%22Desc_ComputerSuper_C%22%3A%2210%22%2C%22Desc_CrystalOscillator_C%22%3A%2210%22%2C%22Desc_TimeCrystal_C%22%3A%22200%22%2C%22Desc_SingularityCell_C%22%3A%2210%22%2C%22Desc_SpaceElevatorPart_6_C%22%3A%226%22%2C%22Desc_SpaceElevatorPart_8_C%22%3A%222%22%7D%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_Diamond_Cloudy_C%22%2C%22Recipe_Alternate_DarkMatter_Trap_C%22%2C%22Recipe_PureAluminumIngot_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%5D%7D)

The byproduct from 2x `Quantum Encoders` with `Neural-Quantum Processor` recipe, 2 `Quantum Encoders` with `Superposition Oscillator` recipe and 1.5 `Quantum Encoders` with `AI Expansion Server` recipe has a byproduct of 550 m3 `Dark Matter Residue` per minute. To produce `Dark Matter Crystals` for the `Superposition Oscillators` and `Ballistic Warp Drives`, I require 350 `Dark Matter Residue`. This is easily covered by the byproduct, but the planner still puts in a separate production line for extra `Dark Matter Residue` being made in a `Converter`. This should not be done. 

Here's an image of the generated production line with the issue highlighted: 
![image](https://github.com/user-attachments/assets/4878f1b5-a6d2-4d11-8176-b4b7a964207e)

**Comment by AnthorNet** [comment]
I believe it was fixed
