### ISSUE TITLE
Steal Pipe Alternate recipes

### ISSUE THREAD

**Issue by Maximum-2007** [AnthorNet/SC-ProductionPlanner#98]
The recipe for 100 Iron Ingots / min for 25 Steal Pipes is missing 
it used to be in there but wehn i relouded the planer to day it wasnt there anymore

**Comment by AnthorNet** [comment]
![image](https://github.com/user-attachments/assets/affeffd7-e0c8-4fd4-b037-300a50e0e6e8)
